### ISSUE TITLE
vis_miss sort_miss = F still changes the order 

### ISSUE THREAD

**Issue by ivanhanigan** [tierneyn/visdat#10]
on https://github.com/tierneyn/visdat/blob/master/R/vis_miss.R#L54
sort_miss is F but you `sort(names(x))`... I showed to a colleague and they felt it confusing as they are used to viewing their data in the native order they usually see it in their spreadsheet.
would you consider something like `if(sort_names == FALSE){ col_order_index <- names(x) } else {col_order_index <- sort(names(x)) }`?

**Comment by tierneyn** [comment]
Yup, I'll have a look at it this evening. I think that it is important the order of the columns matches what you see in the spreadsheet.

**Comment by tierneyn** [comment]
OK changed this with commit [c7ba16e](https://github.com/tierneyn/visdat/commit/c7ba16e26f19bd0f616385ea0520f323fb84ace6), and commit [ae1355f](https://github.com/tierneyn/visdat/commit/ae1355f34d43ad48f36f8fffcb6d6780fd294cf0#diff-e1e1d3d40573127e9ee0480caf1283d6).

This still means that the default behaviour of 

```
vis_dat(df)
``` 

is to arrange the columns by type, but

```
vis_dat(df, order_type = FALSE)
``` 

will now get the same column order as in the dataframe.

Contrary to vis_dat, the default behaviour of 

```
vis_miss(df)
```

will return the "normal" column order, and

```
vis_miss(df, sort_miss = TRUE)
```

Will order by missingness.

This means that the default behaviour of `vis_miss` and `vis_dat` are different to each other, which I don't like entirely, but I can fix that later

**Comment by ivanhanigan** [comment]
working well thanks mate!
