### ISSUE TITLE
Using plotly

### ISSUE THREAD

**Issue by noamross** [tierneyn/visdat#2]
I wonder if you might consider using **plotly** because of core support for interaction - it allows you to hover over a point to get the row number and variable.  Plotly has support for plots created in **ggplot**, but it's not perfect.

Here's my quick hack using the internals from vis_miss.  Unfortunately plotly's `ggplotly()` doesn't yet support `geom_raster()` or `geom_tile()`, so you need o do things manually with `geom_rect()` and do some messing with labels: 
```
library(dplyr)
library(plotly)
data = airquality %>% is.na %>% as.data.frame %>% mutate(rows = row_number()) %>%
  tidyr::gather_(key_col = "variables", value_col = "value",
                 gather_cols = names(.)[-length(.)]) %>%
  mutate(variables = as.factor(variables))

plot = data %>% 
    ggplot(aes(xmin = as.numeric(variables) - 0.5, xmax = as.numeric(variables) + 0.5,
                  ymin = rows - 0.5, ymax = rows + 0.5)) + geom_rect(aes(text = paste(variables, rows, sep=", "), fill = value)) +
  scale_x_discrete(breaks = 1:length(levels(data$variables)), labels = levels(data$variables), expand=c(0,0), range=c(-0.5, length(levels(data$variables) + 0.5))) +
  scale_fill_grey(name = "", labels = c("Present", "Missing")) +
  theme_minimal() + theme(axis.text.x = element_text(angle = 45,
                                                     vjust = 0.5)) + labs(x = "Variables in Dataset", y = "Rows / observations")

plot

ggplotly(plot)
```

I'm sure one can do better, I'm no plotly expert.  It might require making the plots in base plotly rather than using their ggplot conversion mechanism.

**Comment by noamross** [comment]
@cpsievert Is there a way to limit what is displayed in a tooltip in a `ggplotly()` plot?  That is, show what is in the `text=` aesthetic, but not the others?

**Comment by tierneyn** [comment]
Great idea, and thank you for writing the code! That's a pretty serious workaround to geom_tile or geom_raster, nice work. Making interactive plots of this kind of graph is important for exploration and detecting anomalies so I think it would be a great feature! Perhaps it can exist as a separate function (vis_datly), or an internal switch (vis_dat(data, interactive = T)). What do you think? 

Also, I got a little error for the code
```
scale_x_discrete(breaks = 1:length(levels(data$variables)), 
                   labels = levels(data$variables), 
                   expand=c(0,0), 
                   range=c(-0.5, length(levels(data$variables) + 0.5)))
```

This line in particular `range=c(-0.5, length(levels(data$variables) + 0.5)))`  returns the error: 

> Error in levels(data$variables) + 0.5 :   non-numeric argument to binary operator

For the tooltip, I think it'd be really handy to just be able to see what the exact value inside a particular cell is. This way, if something is classed as say a factor, you could see if it is instead clearly a date, or decimal, etc.

On the note of interactivity, what do you think about porting the original [csv fingerprint](http://setosa.io/blog/2014/08/03/csv-fingerprints/) into a htmlwidget?

Thanks again for writing this!

**Comment by cpsievert** [comment]
It will be less of a hack if you use [`plotly(..., type = "heatmap")`](https://plot.ly/r/reference/#heatmap-hoverinfo). You can control the hover-text via the [hoverinfo property](https://plot.ly/r/reference/#heatmap-hoverinfo)

**Comment by cpsievert** [comment]
FYI,  the new version of `ggplotly()` does a much better job of converting now

**Comment by tierneyn** [comment]
Thanks Carson, just tried it, nice! 

```r
library(visdat)
library(plotly) #using the dev version

ggplotly(vis_dat(example2))

```

When I hover over "capacity", I get the caption: 

> (11.50, 7.50 value: integer). 

I assume that this is giving the relative position - it's between columns 11 and 12, and between row 7 and 8, where the value inside here is "integer". Right?

This is cool.

I wonder if it would be possible to map two values onto this, so you can find out that it is an integer, but you can also find out the value of the corresponding data point from the original data. 

Also, missing data does not come up as value: NA when hovering over this, this should be fixed when I assign missing values a consistent name and colour, as in #5 .

So I guess the next question is what should we call it, should it be a separate function?

```r
vis_plotly(example2)
```

Or should it be an option within each `vis_dat`, `vis_miss` and `vis_guess`

```r
vis_dat(example2, interactive = TRUE)
```

**Comment by tierneyn** [comment]
Closing this as @cpsievert pull request https://github.com/tierneyn/visdat/pull/16 fixes this. Thanks Carson!
