### ISSUE TITLE
Use readr:::collectorGuess

### ISSUE THREAD

**Issue by hadley** [tierneyn/visdat#7]
``` r
readr:::collectorGuess("abc", locale_ = readr::locale())
#> [1] "character"
readr:::collectorGuess("1,500", locale_ = readr::locale())
#> [1] "number"
readr:::collectorGuess("2010/10/10", locale_ = readr::locale())
#> [1] "date"
```

It's currently internal, but if you find it useful, I can export it.

**Comment by tierneyn** [comment]
Thanks mate, very much appreciated! I'll have a go this weekend.

**Comment by tierneyn** [comment]
Still investigating...this seems like a potential problem?

```r
readr:::collectorGuess(NA, locale_ = readr::locale())
#> [1] "character"
```

**Comment by hadley** [comment]
Yeah, because it falls back to the most general case. You might want to adjust the behaviour for your case (i.e. check if it's missing first, and return "NA")

**Comment by tierneyn** [comment]
OK done. `vis_guess` uses the utility `guess_type`, instead of `fingerprint`, which `vis_dat` uses. 

I noticed some strange behaviour using `guess_type` though, so I ended up writing `vis_guess` in a bit of a different way.

```r
# > foo <- c(NA, "10", "10.1", "10/01/2001")
# > guess_type(foo)
# [1] NA          "character" "character"
# [4] "character"
#
# > purrr::map_chr(foo, guess_type)
# [1] NA          "integer"   "double"
# [4] "character"
#
# foo_bar <- dplyr::data_frame(x1 = c(NA, "10", "10.1", "10/01/2001"),
#                              x2 = c(NA, "10.1", NA, "FALSE"))
#
# purrr:::map(foo_bar, guess_type)
#
# $x1
# [1] NA          "character" "character"
# [4] "character"
#
# $x2
# [1] NA          "character" NA
# [4] "character"
#
# purrr:::map_chr(foo_bar$x1, guess_type)
#
# [1] NA          "integer"   "double"
# [4] "character"

```

So I apply `purrr::map_chr()` to the `value` column in the long dataframe, which is very slow. 

I feel like I've done something a bit silly/idiotic?

**Comment by hadley** [comment]
I think you want

```R
library(purrr)
map(df, ~ map_chr(., guess_type))
```

**Comment by tierneyn** [comment]
Awesome, thank you Hadley!

I'm definitely using `readr:::collectorGuess`,very useful. Is there a chance you could export it from readr?

**Comment by hadley** [comment]
Yeah - can you file a bug on readr and I'll do it next time I'm working on readr.

**Comment by tierneyn** [comment]
Sure, no problems!

**Comment by tierneyn** [comment]
[done](https://github.com/hadley/readr/issues/377)

**Comment by tierneyn** [comment]
I think I can close this issue as commit https://github.com/tierneyn/visdat/commit/5b31f822f4048fc9f6186b2d3227bfd152987792 created `vis_guess` which uses `readr:::collectorGuess`.

Thanks again mate!
